version: "3.8"

services:
  moeflow-mongodb:
    image: ${DH_DOMAIN}/mongo:4.4.1
    restart: unless-stopped
    volumes:
      - ./mongodb/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    networks:
      - default
    healthcheck:
      test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
      interval: 15s
      timeout: 5s
      start_period: 10s

  moeflow-rabbitmq:
    image: ${DH_DOMAIN}/rabbitmq:3.8.9-management
    restart: unless-stopped
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST_NAME}
    networks:
      - default
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      start_period: 10s

  moeflow-backend: &backend_base
    image: ${GHCR_DOMAIN}/${MOEFLOW_BACKEND_IMAGE}:${MOEFLOW_BACKEND_VERSION}
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage
      - ./logs/moeflow-backend:/app/logs
    environment:
      CONFIG_PATH: "/app/config.py"
    env_file:
      - .env
    networks:
      - default
    depends_on:
      moeflow-backend-init:
        condition: service_completed_successfully
    # NOTE IDK how to easily prepend a pip command with deafult entrypoint/command.
    # Just `docker-compose build` when dep changes.
    command: gunicorn -t 120 -w 4 -b 0.0.0.0:5000 "app:create_app()"

  moeflow-backend-init:
    <<: *backend_base
    command: python3 manage.py migrate
    restart: no
    depends_on: &backend-deps
      moeflow-rabbitmq:
        condition: service_healthy
      moeflow-mongodb:
        condition: service_healthy

  moeflow-celery-default:
    <<: *backend_base
    volumes:
      - ./storage:/app/storage
      - ./logs/moeflow-celery-default:/app/logs
    command: celery --app app.celery worker --queues default --hostname celery.default --loglevel=info

  moeflow-celery-output:
    <<: *backend_base
    volumes:
      - ./storage:/app/storage
      - ./logs/moeflow-celery-output:/app/logs
    command: celery --app app.celery worker --queues output --hostname celery.output --loglevel=info

  moeflow-frontend:
    image: ${GHCR_DOMAIN}/${MOEFLOW_FRONTEND_IMAGE}:${MOEFLOW_FRONTEND_VERSION}
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/certificates:/certificates
      - ./storage:/storage
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    environment:
      DOMAIN: ${DOMAIN}
      MAX_CONTENT_LENGTH_MB: ${MAX_CONTENT_LENGTH_MB}
    links: [moeflow-backend]
    networks:
      - default

networks:
  default:
    name: moeflow
