version: "3.8"

services:
  moeflow-mongodb:
    image: ${DH_DOMAIN}/mongo:4.4.1
    restart: unless-stopped
    volumes:
      - ./mongodb/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    networks:
      - default

  moeflow-rabbitmq:
    image: ${DH_DOMAIN}/rabbitmq:3.8.9-management
    restart: unless-stopped
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST_NAME}
    networks:
      - default

  moeflow-backend:
    image: ${GHCR_DOMAIN}/kozzzx/moeflow-backend:${MOEFLOW_BACKEND_VERSION}
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage
      - ./logs/moeflow-backend:/app/logs
    environment:
      CONFIG_PATH: "/app/config.py"
    env_file:
      - .env
    networks:
      - default
    command: gunicorn -t 120 -w 4 -b 0.0.0.0:5000 "app:create_app()"

  moeflow-celery-default:
    image: ${GHCR_DOMAIN}/kozzzx/moeflow-backend:${MOEFLOW_BACKEND_VERSION}
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage
      - ./logs/moeflow-celery-default:/app/logs
    environment:
      CONFIG_PATH: "/app/config.py"
    env_file:
      - .env
    networks:
      - default
    command: celery -A app.celery worker -n default --loglevel=info

  moeflow-celery-output:
    image: ${GHCR_DOMAIN}/kozzzx/moeflow-backend:${MOEFLOW_BACKEND_VERSION}
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage
      - ./logs/moeflow-celery-output:/app/logs
    environment:
      CONFIG_PATH: "/app/config.py"
    env_file:
      - .env
    networks:
      - default
    command: celery -A app.celery worker -Q output -n output --loglevel=info

  moeflow-frontend:
    image: ${GHCR_DOMAIN}/kozzzx/moeflow-frontend:${MOEFLOW_FRONTEND_VERSION}
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/certificates:/certificates
      - ./storage:/storage
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    environment:
      DOMAIN: ${DOMAIN}
      MAX_CONTENT_LENGTH_MB: ${MAX_CONTENT_LENGTH_MB}
    networks:
      - default

networks:
  default:
    name: moeflow
