# Update labelplus latest releases to OSS

name: Update labelplus latest releases

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Assets
        uses: houqp/download-release-assets-action@v1.0.1
        with:
          repo: LabelPlus/PS-Script
          match: "LabelPlus_PS-Script_.+"
          rename: LabelPlus_PS-Script_latest.7z
      - run: sudo apt -y install atool
      - run: mkdir releases
      - run: arepack -e -F zip ./releases/LabelPlus_PS-Script_latest.7z
      - name: Upload to oss
        id: upload_to_oss
        uses: tvrcgo/upload-to-oss@v0.1.1
        with:
          key-id: ${{ secrets.MOEFLOW_STATIC_OSS_KEY_ID }}
          key-secret: ${{ secrets.MOEFLOW_STATIC_OSS_KEY_SECRET }}
          region: oss-cn-shanghai
          bucket: moeflow-static
          asset-path: ./releases
          target-path: /releases/
